cache:
  enabled: true
  db_file: /tmp/cache.db
  reader:
    host: localhost
    front_end:
      protocol: tcp
      port: 7777
    back_end:
      protocol: tcp
      port: 7778
    num_workers: 4
  writer:
    host: localhost
    front_end:
      protocol: tcp
      port: 7779
    back_end:
      protocol: tcp
      port: 7780
llm:
  enabled: true
  front_end:
    host: localhost
    protocol: tcp
    port: 7781
  back_end:
    host: localhost
    protocol: tcp
    port: 7782
  num_workers: 1
  base_model_file: /media/yueyulin/KINGSTON/models/rwkv6/RWKV-x060-World-1B6-v2.1-20240328-ctx4096.pth
  bi_lora_path: /media/yueyulin/KINGSTON/models/rwkv6/lora/bi-encoder/add_mlp_in_batch_neg/epoch_0_step_200000/RWKV-x060-World-1B6-v2.1-20240328-ctx4096.pth.pth
  cross_lora_path: /media/yueyulin/KINGSTON/models/rwkv6/lora/cross-encoder/epoch_0_step_500000/RWKV-x060-World-1B6-v2.1-20240328-ctx4096.pth.pth
  tokenizer_file: /home/yueyulin/github/RWKV_LM_EXT/tokenizer/rwkv_vocab_v20230424.txt
  device: cuda:0
indexing:
  enabled: true
  front_end:
    host: localhost
    protocol: tcp
    port: 7783
  back_end:
    host: localhost
    protocol: tcp
    port: 7784
  chroma_path: /home/yueyulin/tmp/chroma_data
  chroma_port: 9999
  chroma_host: localhost
  num_workers: 4
  llm_front_end_url: tcp://localhost:7781